import BeneficiariesRegistrationManualFormData from './beneficiariesRegistrationManualFormData'
import BeneficiariesRegistrationManualFormBonds from './beneficiariesRegistrationManualFormBonds'
import BeneficiariesRegistrationManualFormContractor from './beneficiariesRegistrationManualFormContractor'
import BeneficiariesRegistrationManualFormCaregiver from './beneficiariesRegistrationManualFormCaregiver'
import MonitorRegistrationFormData from './monitorRegistrationFormData'
import MonitorRegistrationManualFormBonds from './monitorRegistrationManualFormBonds'

export {
  BeneficiariesRegistrationManualFormData,
  BeneficiariesRegistrationManualFormBonds,
  BeneficiariesRegistrationManualFormContractor,
  BeneficiariesRegistrationManualFormCaregiver,
  MonitorRegistrationFormData,
  MonitorRegistrationManualFormBonds,
}
